version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - STORAGE_TYPE=local
    depends_on:
      - weaviate

  ui:
    build:
      context: ../web-ui
      dockerfile: ../docker/Dockerfile.ui
    ports:
      - "3000:3000"
    depends_on:
      - api

  weaviate:
    image: semitechnologies/weaviate:1.19.0
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: 